server:
  port: ${PORT:8080}

spring:
  application:
    name: otelier-backend
  
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://username:password@cluster.mongodb.net/otelier?retryWrites=true&w=majority}
      database: otelier
  
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: ${SENDGRID_API_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Supabase Configuration
supabase:
  jwt:
    secret: ${SUPABASE_JWT_SECRET}
    issuer: ${SUPABASE_URL:https://your-project.supabase.co}

# Notification Configuration
notification:
  support-email: ${SUPPORT_EMAIL:support@otelier.com}
  from-email: ${FROM_EMAIL:noreply@otelier.com}

# Logging
logging:
  level:
    com.otelier: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] - %msg%n"

# Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
